import {
  cilAt,
  cilLockLocked,
  cilUser,
  cilChartLine,
  cilMenu,
  cilCart,
  cilSettings,
  cilAccountLogout,
  cilDescription,
  cilFastfood,
  cilArrowCircleLeft,
  cilMinus,
  cilPlus,
  cilTrash,
} from '@coreui/icons';

export const iconSubset = {
  cilAt,
  cilTrash,
  cilMinus,
  cilPlus,
  cilLockLocked,
  cilUser,
  cilChartLine,
  cilMenu,
  cilCart,
  cilSettings,
  cilAccountLogout,
  cilDescription,
  cilFastfood,
  cilArrowCircleLeft,
};

export enum EIconSubset {
  cilAt = 'cilAt',
  cilLockLocked = 'cilLockLocked',
  cilUser = 'cilUser',
  cilChartLine = 'cilChartLine',
  cilMenu = 'cilMenu',
  cilCart = 'cilCart',
  cilSettings = 'cilSettings',
  cilAccountLogout = 'cilAccountLogout',
  cilDescription = 'cilDescription',
  cilFastfood = 'cilFastfood',
  cilArrowCircleLeft = 'cilArrowCircleLeft',
  cilMinus = 'cilMinus',
  cilPlus = 'cilPlus',
  cilTrash = 'cilTrash',
}
